# Generated by Django 5.1.5 on 2025-01-21 05:40

import django.db.models.deletion
from django.conf import settings
from django.db import migrations, models


class Migration(migrations.Migration):

    initial = True

    dependencies = [
        migrations.swappable_dependency(settings.AUTH_USER_MODEL),
    ]

    operations = [
        migrations.CreateModel(
            name="Habits",
            fields=[
                (
                    "id",
                    models.BigAutoField(
                        auto_created=True,
                        primary_key=True,
                        serialize=False,
                        verbose_name="ID",
                    ),
                ),
                (
                    "name",
                    models.CharField(
                        max_length=100, unique=True, verbose_name="Название привычки"
                    ),
                ),
                (
                    "place",
                    models.CharField(
                        help_text="Введите место, где нужно выполнить привычку, например - Дом.",
                        max_length=100,
                        verbose_name="Место",
                    ),
                ),
                (
                    "is_nice_habit",
                    models.BooleanField(
                        default=False, help_text="Это приятная привычка?"
                    ),
                ),
                (
                    "related_habit",
                    models.CharField(
                        blank=True,
                        help_text="Введите привычку с которой хотите связать текущую.",
                        max_length=100,
                        null=True,
                        verbose_name="связанная привычка",
                    ),
                ),
                (
                    "period",
                    models.PositiveIntegerField(
                        blank=True,
                        help_text="Ведите кол-ва дней через которое вам нужно будет напоминать.",
                        null=True,
                        verbose_name="Частота напоминаний в днях",
                    ),
                ),
                (
                    "date_created",
                    models.DateTimeField(
                        auto_now_add=True, verbose_name="Дата создания"
                    ),
                ),
                (
                    "reward",
                    models.TextField(
                        blank=True,
                        help_text="Введите вознаграждение за выполнение привычки",
                        null=True,
                        verbose_name="Вознаграждение",
                    ),
                ),
                (
                    "time_to_do",
                    models.TimeField(
                        help_text="Введите примерное время для выполнения привычки",
                        verbose_name="Время на выполнение привычки",
                    ),
                ),
                (
                    "is_public",
                    models.BooleanField(
                        default=False,
                        help_text="Могут ли эту привычку видеть другие пользователи?",
                        verbose_name="Признак публичности",
                    ),
                ),
                (
                    "owner",
                    models.ForeignKey(
                        on_delete=django.db.models.deletion.CASCADE,
                        related_name="habits",
                        to=settings.AUTH_USER_MODEL,
                    ),
                ),
            ],
        ),
    ]
