# Generated by Django 5.1.5 on 2025-01-22 04:55

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ("habits", "0001_initial"),
    ]

    operations = [
        migrations.AddField(
            model_name="habits",
            name="time_length",
            field=models.PositiveIntegerField(
                default=1,
                help_text="Введите примерное время для выполнения привычки в минутах",
                verbose_name="Время на выполнение привычки",
            ),
        ),
        migrations.AlterField(
            model_name="habits",
            name="time_to_do",
            field=models.TimeField(
                help_text="Введите время во сколько вы планируете начинать привычку",
                verbose_name="Время начала привычки",
            ),
        ),
    ]
