# Generated by Django 5.1.5 on 2025-01-22 05:48

import django.db.models.deletion
from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ("habits", "0002_habits_time_length_alter_habits_time_to_do"),
    ]

    operations = [
        migrations.AlterField(
            model_name="habits",
            name="related_habit",
            field=models.ForeignKey(
                blank=True,
                help_text="Введите привычку с которой хотите связать текущую.",
                max_length=100,
                null=True,
                on_delete=django.db.models.deletion.CASCADE,
                to="habits.habits",
                verbose_name="связанная привычка",
            ),
        ),
    ]
