# Generated by Django 5.1.5 on 2025-01-25 08:18

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ("habits", "0004_alter_habits_owner"),
    ]

    operations = [
        migrations.AddField(
            model_name="habits",
            name="last_remind",
            field=models.DateTimeField(
                default="1900-01-01 12:00", verbose_name="последнее напоминание"
            ),
        ),
    ]
